//
// This file was pubmed.openAccess.jaxb.generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.04 at 07:58:30 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.w3.org/1998/Math/MathML", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package elsevier.jaxb.math.mathml;
