/**
 * pubmed.endNote.jaxb.generated by http://RDFReactor.semweb4j.org ($Id: CodeGenerator.java 1535 2008-09-09 15:44:46Z max.at.xam.de $) on 13/01/11 08:05 PM
 */
package ws.biotea.ld2rdf.rdf.model.bibo;

import org.ontoware.aifbcommons.collection.ClosableIterator;
import org.ontoware.rdf2go.exception.ModelRuntimeException;
import org.ontoware.rdf2go.model.Model;
import org.ontoware.rdf2go.model.node.BlankNode;
import org.ontoware.rdf2go.model.node.URI;
import org.ontoware.rdf2go.model.node.impl.URIImpl;
import org.ontoware.rdfreactor.runtime.Base;
import org.ontoware.rdfreactor.runtime.ReactorResult;

/**
 * This class manages access to these properties:
 * <ul>
 *   <li> AffirmedBy </li>
 *   <li> ReversedBy </li>
 *   <li> SubsequentLegalDecision </li>
 * </ul>
 *
 * This class was pubmed.endNote.jaxb.generated by <a href="http://RDFReactor.semweb4j.org">RDFReactor</a> on 13/01/11 08:05 PM
 */
public class Decision extends LegalCaseDocument {

    /** http://purl.org/ontology/bibo/LegalDecision */
    @SuppressWarnings("hiding")
	public static final URI RDFS_CLASS = new URIImpl("http://purl.org/ontology/bibo/LegalDecision", false);

    /** http://purl.org/ontology/bibo/affirmedBy */
    @SuppressWarnings("hiding")
	public static final URI AFFIRMEDBY = new URIImpl("http://purl.org/ontology/bibo/affirmedBy",false);

    /** http://purl.org/ontology/bibo/reversedBy */
    @SuppressWarnings("hiding")
	public static final URI REVERSEDBY = new URIImpl("http://purl.org/ontology/bibo/reversedBy",false);

    /** http://purl.org/ontology/bibo/subsequentLegalDecision */
    @SuppressWarnings("hiding")
	public static final URI SUBSEQUENTLEGALDECISION = new URIImpl("http://purl.org/ontology/bibo/subsequentLegalDecision",false);

    /** 
     * All property-URIs with this class as domain.
     * All properties of all super-classes are also available. 
     */
    @SuppressWarnings("hiding")
    public static final URI[] MANAGED_URIS = {
      new URIImpl("http://purl.org/ontology/bibo/affirmedBy",false),
      new URIImpl("http://purl.org/ontology/bibo/reversedBy",false),
      new URIImpl("http://purl.org/ontology/bibo/subsequentLegalDecision",false) 
    };


	// protected constructors needed for inheritance
	
	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.semweb4j.org
	 * @param classURI URI of RDFS class
	 * @param instanceIdentifier Resource that identifies this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c1] 
	 */
	protected Decision ( Model model, URI classURI, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, classURI, instanceIdentifier, write);
	}

	// public constructors

	/**
	 * Returns a Java wrapper over an RDF object, identified by URI.
	 * Creating two wrappers for the same instanceURI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param instanceIdentifier an RDF2Go Resource identifying this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c2] 
	 */
	public Decision ( Model model, org.ontoware.rdf2go.model.node.Resource instanceIdentifier, boolean write ) {
		super(model, RDFS_CLASS, instanceIdentifier, write);
	}


	/**
	 * Returns a Java wrapper over an RDF object, identified by a URI, given as a String.
	 * Creating two wrappers for the same URI is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param uriString a URI given as a String
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 * @throws ModelRuntimeException if URI syntax is wrong
	 *
	 * [Generated from RDFReactor template rule #c7] 
	 */
	public Decision ( Model model, String uriString, boolean write) throws ModelRuntimeException {
		super(model, RDFS_CLASS, new URIImpl(uriString,false), write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by a blank node.
	 * Creating two wrappers for the same blank node is legal.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param bnode BlankNode of this instance
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c8] 
	 */
	public Decision ( Model model, BlankNode bnode, boolean write ) {
		super(model, RDFS_CLASS, bnode, write);
	}

	/**
	 * Returns a Java wrapper over an RDF object, identified by 
	 * a randomly pubmed.endNote.jaxb.generated URI.
	 * Creating two wrappers results in different URIs.
	 * @param model RDF2GO Model implementation, see http://rdf2go.ontoware.org
	 * @param write if true, the statement (this, rdf:type, TYPE) is written to the model
	 *
	 * [Generated from RDFReactor template rule #c9] 
	 */
	public Decision ( Model model, boolean write ) {
		super(model, RDFS_CLASS, model.newRandomUniqueURI(), write);
	}

    ///////////////////////////////////////////////////////////////////
    // typing

	/**
	 * Return an existing instance of this class in the model. No statements are written.
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return an instance of Decision  or null if none existst
	 *
	 * [Generated from RDFReactor template rule #class0] 
	 */
	public static Decision  getInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getInstance(model, instanceResource, Decision.class);
	}

	/**
	 * Create a new instance of this class in the model. 
	 * That is, create the statement (instanceResource, RDF.type, http://purl.org/ontology/bibo/LegalDecision).
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class1] 
	 */
	public static void createInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.createInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 * @return true if instanceResource is an instance of this class in the model
	 *
	 * [Generated from RDFReactor template rule #class2] 
	 */
	public static boolean hasInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.hasInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as RDF resources
	 *
	 * [Generated from RDFReactor template rule #class3] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllInstances(Model model) {
		return Base.getAllInstances(model, RDFS_CLASS, org.ontoware.rdf2go.model.node.Resource.class);
	}

	/**
	 * @param model an RDF2Go model
	 * @return all instances of this class in Model 'model' as a ReactorResult,
	 * which can conveniently be converted to iterator, list or array.
	 *
	 * [Generated from RDFReactor template rule #class3-as] 
	 */
	public static ReactorResult<? extends Decision> getAllInstances_as(Model model) {
		return Base.getAllInstances_as(model, RDFS_CLASS, Decision.class );
	}

    /**
	 * Remove rdf:type Decision from this instance. Other triples are not affected.
	 * To delete more, use deleteAllProperties
	 * @param model an RDF2Go model
	 * @param instanceResource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #class4] 
	 */
	public static void deleteInstance(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteInstance(model, RDFS_CLASS, instanceResource);
	}

	/**
	 * Delete all (this, *, *), i.e. including rdf:type
	 * @param model an RDF2Go model
	 * @param resource
	 */
	public static void deleteAllProperties(Model model,	org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.deleteAllProperties(model, instanceResource);
	}

    ///////////////////////////////////////////////////////////////////
    // property access methods

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'AffirmedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboAffirmedBy_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Decision.AFFIRMEDBY, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'AffirmedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboAffirmedBy_Inverse() {
		return Base.getAll_Inverse(this.model, Decision.AFFIRMEDBY, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'AffirmedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllbiboAffirmedBy_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Decision.AFFIRMEDBY, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}


	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'ReversedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboReversedBy_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Decision.REVERSEDBY, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'ReversedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboReversedBy_Inverse() {
		return Base.getAll_Inverse(this.model, Decision.REVERSEDBY, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'ReversedBy' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllbiboReversedBy_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Decision.REVERSEDBY, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}


	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as RDF resources, that have a relation 'SubsequentLegalDecision' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1static] 
	 */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboSubsequentLegalDecision_Inverse( Model model, Object objectValue) {
		return Base.getAll_Inverse(model, Decision.SUBSEQUENTLEGALDECISION, objectValue);
	}

	/**
	 * @return all A's as RDF resources, that have a relation 'SubsequentLegalDecision' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse1dynamic] 
	 */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Resource> getAllbiboSubsequentLegalDecision_Inverse() {
		return Base.getAll_Inverse(this.model, Decision.SUBSEQUENTLEGALDECISION, this.getResource() );
	}

	/**
	 * @param model an RDF2Go model
	 * @param objectValue
	 * @return all A's as a ReactorResult, that have a relation 'SubsequentLegalDecision' to this Decision instance
	 *
	 * [Generated from RDFReactor template rule #getallinverse-as1static] 
	 */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Resource> getAllbiboSubsequentLegalDecision_Inverse_as( Model model, Object objectValue) {
		return Base.getAll_Inverse_as(model, Decision.SUBSEQUENTLEGALDECISION, objectValue, org.ontoware.rdf2go.model.node.Resource.class);
	}



    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1d46dda has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasbiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, AFFIRMEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1d46dda has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasbiboAffirmedBy() {
		return Base.has(this.model, this.getResource(), AFFIRMEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1d46dda has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasbiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, AFFIRMEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1d46dda has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasbiboAffirmedBy( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), AFFIRMEDBY);
	}

     /**
     * Get all values of property AffirmedBy as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboAffirmedBy_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, AFFIRMEDBY);
	}
	
    /**
     * Get all values of property AffirmedBy as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboAffirmedBy_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, AFFIRMEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property AffirmedBy as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboAffirmedBy_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), AFFIRMEDBY);
	}

    /**
     * Get all values of property AffirmedBy as a ReactorResult of RDF2Go nodes 
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboAffirmedBy_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), AFFIRMEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property AffirmedBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Decision> getAllbiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, AFFIRMEDBY, Decision.class);
	}
	
    /**
     * Get all values of property AffirmedBy as a ReactorResult of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Decision> getAllbiboAffirmedBy_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, AFFIRMEDBY, Decision.class);
	}

    /**
     * Get all values of property AffirmedBy     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Decision> getAllbiboAffirmedBy() {
		return Base.getAll(this.model, this.getResource(), AFFIRMEDBY, Decision.class);
	}

    /**
     * Get all values of property AffirmedBy as a ReactorResult of Decision 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Decision> getAllbiboAffirmedBy_as() {
		return Base.getAll_as(this.model, this.getResource(), AFFIRMEDBY, Decision.class);
	}
 
    /**
     * Adds a value to property AffirmedBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addbiboAffirmedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Adds a value to property AffirmedBy as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addbiboAffirmedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), AFFIRMEDBY, value);
	}
    /**
     * Adds a value to property AffirmedBy from an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addbiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.add(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Adds a value to property AffirmedBy from an instance of Decision 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addbiboAffirmedBy(Decision value) {
		Base.add(this.model, this.getResource(), AFFIRMEDBY, value);
	}
  

    /**
     * Sets a value of property AffirmedBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setbiboAffirmedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Sets a value of property AffirmedBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setbiboAffirmedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), AFFIRMEDBY, value);
	}
    /**
     * Sets a value of property AffirmedBy from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setbiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.set(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Sets a value of property AffirmedBy from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setbiboAffirmedBy(Decision value) {
		Base.set(this.model, this.getResource(), AFFIRMEDBY, value);
	}
  


    /**
     * Removes a value of property AffirmedBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removebiboAffirmedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Removes a value of property AffirmedBy as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removebiboAffirmedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), AFFIRMEDBY, value);
	}
    /**
     * Removes a value of property AffirmedBy given as an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removebiboAffirmedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.remove(model, instanceResource, AFFIRMEDBY, value);
	}
	
    /**
     * Removes a value of property AffirmedBy given as an instance of Decision 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removebiboAffirmedBy(Decision value) {
		Base.remove(this.model, this.getResource(), AFFIRMEDBY, value);
	}
  
    /**
     * Removes all values of property AffirmedBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllbiboAffirmedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, AFFIRMEDBY);
	}
	
    /**
     * Removes all values of property AffirmedBy	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllbiboAffirmedBy() {
		Base.removeAll(this.model, this.getResource(), AFFIRMEDBY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1950f08 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasbiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, REVERSEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1950f08 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasbiboReversedBy() {
		return Base.has(this.model, this.getResource(), REVERSEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1950f08 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasbiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, REVERSEDBY);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1950f08 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasbiboReversedBy( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), REVERSEDBY);
	}

     /**
     * Get all values of property ReversedBy as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboReversedBy_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, REVERSEDBY);
	}
	
    /**
     * Get all values of property ReversedBy as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboReversedBy_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, REVERSEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property ReversedBy as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboReversedBy_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), REVERSEDBY);
	}

    /**
     * Get all values of property ReversedBy as a ReactorResult of RDF2Go nodes 
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboReversedBy_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), REVERSEDBY, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property ReversedBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Decision> getAllbiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, REVERSEDBY, Decision.class);
	}
	
    /**
     * Get all values of property ReversedBy as a ReactorResult of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Decision> getAllbiboReversedBy_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, REVERSEDBY, Decision.class);
	}

    /**
     * Get all values of property ReversedBy     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Decision> getAllbiboReversedBy() {
		return Base.getAll(this.model, this.getResource(), REVERSEDBY, Decision.class);
	}

    /**
     * Get all values of property ReversedBy as a ReactorResult of Decision 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Decision> getAllbiboReversedBy_as() {
		return Base.getAll_as(this.model, this.getResource(), REVERSEDBY, Decision.class);
	}
 
    /**
     * Adds a value to property ReversedBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addbiboReversedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Adds a value to property ReversedBy as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addbiboReversedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), REVERSEDBY, value);
	}
    /**
     * Adds a value to property ReversedBy from an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addbiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.add(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Adds a value to property ReversedBy from an instance of Decision 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addbiboReversedBy(Decision value) {
		Base.add(this.model, this.getResource(), REVERSEDBY, value);
	}
  

    /**
     * Sets a value of property ReversedBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setbiboReversedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Sets a value of property ReversedBy from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setbiboReversedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), REVERSEDBY, value);
	}
    /**
     * Sets a value of property ReversedBy from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setbiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.set(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Sets a value of property ReversedBy from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setbiboReversedBy(Decision value) {
		Base.set(this.model, this.getResource(), REVERSEDBY, value);
	}
  


    /**
     * Removes a value of property ReversedBy as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removebiboReversedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Removes a value of property ReversedBy as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removebiboReversedBy( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), REVERSEDBY, value);
	}
    /**
     * Removes a value of property ReversedBy given as an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removebiboReversedBy(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.remove(model, instanceResource, REVERSEDBY, value);
	}
	
    /**
     * Removes a value of property ReversedBy given as an instance of Decision 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removebiboReversedBy(Decision value) {
		Base.remove(this.model, this.getResource(), REVERSEDBY, value);
	}
  
    /**
     * Removes all values of property ReversedBy     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllbiboReversedBy( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, REVERSEDBY);
	}
	
    /**
     * Removes all values of property ReversedBy	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllbiboReversedBy() {
		Base.removeAll(this.model, this.getResource(), REVERSEDBY);
	}
     /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1935fa6 has at least one value set 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-static] 
     */
	public static boolean hasbiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.has(model, instanceResource, SUBSEQUENTLEGALDECISION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1935fa6 has at least one value set 
     * @return true if this property has at least one value
	 *
	 * [Generated from RDFReactor template rule #get0has-dynamic] 
     */
	public boolean hasbiboSubsequentLegalDecision() {
		return Base.has(this.model, this.getResource(), SUBSEQUENTLEGALDECISION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1935fa6 has the given value (maybe among other values).  
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-static] 
     */
	public static boolean hasbiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(model, instanceResource, SUBSEQUENTLEGALDECISION);
	}

    /**
     * Check if org.ontoware.rdfreactor.generator.java.JProperty@1935fa6 has the given value (maybe among other values).  
	 * @param value the value to be checked
     * @return true if this property contains (maybe among other) the given value
	 *
	 * [Generated from RDFReactor template rule #get0has-value-dynamic] 
     */
	public boolean hasbiboSubsequentLegalDecision( org.ontoware.rdf2go.model.node.Node value ) {
		return Base.hasValue(this.model, this.getResource(), SUBSEQUENTLEGALDECISION);
	}

     /**
     * Get all values of property SubsequentLegalDecision as an Iterator over RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static] 
     */
	public static ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboSubsequentLegalDecision_asNode(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_asNode(model, instanceResource, SUBSEQUENTLEGALDECISION);
	}
	
    /**
     * Get all values of property SubsequentLegalDecision as a ReactorResult of RDF2Go nodes 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get7static-reactor-result] 
     */
	public static ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboSubsequentLegalDecision_asNode_(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, SUBSEQUENTLEGALDECISION, org.ontoware.rdf2go.model.node.Node.class);
	}

    /**
     * Get all values of property SubsequentLegalDecision as an Iterator over RDF2Go nodes 
     * @return a ClosableIterator of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic] 
     */
	public ClosableIterator<org.ontoware.rdf2go.model.node.Node> getAllbiboSubsequentLegalDecision_asNode() {
		return Base.getAll_asNode(this.model, this.getResource(), SUBSEQUENTLEGALDECISION);
	}

    /**
     * Get all values of property SubsequentLegalDecision as a ReactorResult of RDF2Go nodes 
     * @return a ListE of RDF2Go Nodes
	 *
	 * [Generated from RDFReactor template rule #get8dynamic-reactor-result] 
     */
	public ReactorResult<org.ontoware.rdf2go.model.node.Node> getAllbiboSubsequentLegalDecision_asNode_() {
		return Base.getAll_as(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, org.ontoware.rdf2go.model.node.Node.class);
	}
     /**
     * Get all values of property SubsequentLegalDecision     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get11static] 
     */
	public static ClosableIterator<Decision> getAllbiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll(model, instanceResource, SUBSEQUENTLEGALDECISION, Decision.class);
	}
	
    /**
     * Get all values of property SubsequentLegalDecision as a ReactorResult of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get11static-reactorresult] 
     */
	public static ReactorResult<Decision> getAllbiboSubsequentLegalDecision_as(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		return Base.getAll_as(model, instanceResource, SUBSEQUENTLEGALDECISION, Decision.class);
	}

    /**
     * Get all values of property SubsequentLegalDecision     * @return a ClosableIterator of $type
	 *
	 * [Generated from RDFReactor template rule #get12dynamic] 
     */
	public ClosableIterator<Decision> getAllbiboSubsequentLegalDecision() {
		return Base.getAll(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, Decision.class);
	}

    /**
     * Get all values of property SubsequentLegalDecision as a ReactorResult of Decision 
     * @return a ReactorResult of $type which can conveniently be converted to iterator, list or array
	 *
	 * [Generated from RDFReactor template rule #get12dynamic-reactorresult] 
     */
	public ReactorResult<Decision> getAllbiboSubsequentLegalDecision_as() {
		return Base.getAll_as(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, Decision.class);
	}
 
    /**
     * Adds a value to property SubsequentLegalDecision as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1static] 
     */
	public static void addbiboSubsequentLegalDecision( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.add(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Adds a value to property SubsequentLegalDecision as an RDF2Go node 
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #add1dynamic] 
     */
	public void addbiboSubsequentLegalDecision( org.ontoware.rdf2go.model.node.Node value) {
		Base.add(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
    /**
     * Adds a value to property SubsequentLegalDecision from an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #add3static] 
     */
	public static void addbiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.add(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Adds a value to property SubsequentLegalDecision from an instance of Decision 
	 *
	 * [Generated from RDFReactor template rule #add4dynamic] 
     */
	public void addbiboSubsequentLegalDecision(Decision value) {
		Base.add(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
  

    /**
     * Sets a value of property SubsequentLegalDecision from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be set
	 *
	 * [Generated from RDFReactor template rule #set1static] 
     */
	public static void setbiboSubsequentLegalDecision( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.set(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Sets a value of property SubsequentLegalDecision from an RDF2Go node.
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set1dynamic] 
     */
	public void setbiboSubsequentLegalDecision( org.ontoware.rdf2go.model.node.Node value) {
		Base.set(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
    /**
     * Sets a value of property SubsequentLegalDecision from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set3static] 
     */
	public static void setbiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.set(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Sets a value of property SubsequentLegalDecision from an instance of Decision 
     * First, all existing values are removed, then this value is added.
     * Cardinality constraints are not checked, but this method exists only for properties with
     * no minCardinality or minCardinality == 1.
	 * @param value the value to be added
	 *
	 * [Generated from RDFReactor template rule #set4dynamic] 
     */
	public void setbiboSubsequentLegalDecision(Decision value) {
		Base.set(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
  


    /**
     * Removes a value of property SubsequentLegalDecision as an RDF2Go node 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1static] 
     */
	public static void removebiboSubsequentLegalDecision( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Removes a value of property SubsequentLegalDecision as an RDF2Go node
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove1dynamic] 
     */
	public void removebiboSubsequentLegalDecision( org.ontoware.rdf2go.model.node.Node value) {
		Base.remove(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
    /**
     * Removes a value of property SubsequentLegalDecision given as an instance of Decision 
     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove3static] 
     */
	public static void removebiboSubsequentLegalDecision(Model model, org.ontoware.rdf2go.model.node.Resource instanceResource, Decision value) {
		Base.remove(model, instanceResource, SUBSEQUENTLEGALDECISION, value);
	}
	
    /**
     * Removes a value of property SubsequentLegalDecision given as an instance of Decision 
	 * @param value the value to be removed
	 *
	 * [Generated from RDFReactor template rule #remove4dynamic] 
     */
	public void removebiboSubsequentLegalDecision(Decision value) {
		Base.remove(this.model, this.getResource(), SUBSEQUENTLEGALDECISION, value);
	}
  
    /**
     * Removes all values of property SubsequentLegalDecision     * @param model an RDF2Go model
     * @param resource an RDF2Go resource
	 *
	 * [Generated from RDFReactor template rule #removeall1static] 
     */
	public static void removeAllbiboSubsequentLegalDecision( Model model, org.ontoware.rdf2go.model.node.Resource instanceResource) {
		Base.removeAll(model, instanceResource, SUBSEQUENTLEGALDECISION);
	}
	
    /**
     * Removes all values of property SubsequentLegalDecision	 *
	 * [Generated from RDFReactor template rule #removeall1dynamic] 
     */
	public void removeAllbiboSubsequentLegalDecision() {
		Base.removeAll(this.model, this.getResource(), SUBSEQUENTLEGALDECISION);
	}
 }